### ISSUE TITLE
Create new HTML 5 backend layout

### ISSUE THREAD

**Issue by mvdkleijn** [wolfcms/wolfcms#346]
This issue is to record a new feature development: the default Wolf CMS backend layout should be based on HTML 5.

**Comment by mtylerb** [comment]
Has this been put on the back burner?  Are there any special requirements that need to be met for a push to be accepted?  A friend of mine and I were going to work on this for one of my sites, but I don't want this to get overwritten once updates are issued.  I'm familiar with Wolf's core and he's a whiz with Bootstrap, so...

Thoughts?

**Comment by mtylerb** [comment]
So apparently he's already been working on the login script...  https://www.ehpluselectric.com/admin/login if you're interested in looking.

**Comment by project79** [comment]
We gave up on bootstrap as it would screw a lot of backward compatibility with plugins and went for more "lighter" approach. This is already pass it's deadline long time ago but I really did not had any free time to sort it out and finish. 
A lot of things has changed and it took me some time to clean html and unify it for more generic css.

Here's a preview of the login form: http://five.medio.com.hr/?/admin/login

**Comment by mvdkleijn** [comment]
Nevertheless that login screen does look nice. @mtylerb Though we did not go the Bootstrap way, I have no problem with someone making a bootstrap version based on the new cleaned up backend once we release it (if you manage / want to).

**Comment by mtylerb** [comment]
By plugins, are you referring to third party, core or both? Is there any way we could implement a fallback system where we keep the light html5 for plugins that haven't been updated and put a new bootstrap version in place that new plugins can use.

Maybe a deprecation notice to developers and give them until 0.9.x before it fully switches to completely bootstrap backend. I'd be happy to help with implementation of the Bootstrap side along with the fallback system if it is something you're interested in.

**Comment by project79** [comment]
For both plugins, core and third-party. Even with the new backend, you will need to change few small things (like sidebar buttons, as there will be fontawesome icons instead of current images).

Moving to Bootstrap is not worth the trouble (trust me, I've done it). There is simply too much to do and html becomes bloatware and I doubt that people will change all their plugins to make it look good. 

New styles have everything you need and use pure html elements without any extra classes, unlike Bootstrap. Since it's made with SASS it is easy to add new stuff in it. New stuff will be available next week (I hope) for testing and feedback.

The best option for Bootstrap now is to create a theme that will override core styles.

**Comment by mtylerb** [comment]
So after a little bit of playing around, we managed to get the admin section working with Bootstrap.  Granted this is with the old 0.8.3.1 backend, minor changes were made in 6 of the admin files.  None of the plugins seem to have broken.  The only caveat is it isn't 100% responsive.  Don't get me wrong, it's close, but there were some words written over other words when viewing the page on my cell phone.

Screenshot showing one of my plugins I am working on under the old 0.8.3.1 system.  Shows the sidebar, etc:
![screenshot 1](https://cloud.githubusercontent.com/assets/525623/9398393/06e2994a-4764-11e5-88f9-3dd311097dfd.png)

Screenshot showing the login screen:
![screenshot 4](https://cloud.githubusercontent.com/assets/525623/9398488/d49ab7aa-4764-11e5-9341-10fe3326a883.png)

Screenshot showing the File Manager plugin:
![screenshot 3](https://cloud.githubusercontent.com/assets/525623/9398487/d4971456-4764-11e5-8ea4-e3b1aa82045f.png)

I'd be interested in seeing the new backend layout so we can see if we can modify it as easily.

**Comment by project79** [comment]
Here are some screenshots:

Login:
![login](https://cloud.githubusercontent.com/assets/493458/9402793/0c5d76c4-47e1-11e5-984c-146d5b572bd0.png)

Pages:
![pages](https://cloud.githubusercontent.com/assets/493458/9402805/2a0e4248-47e1-11e5-9bb4-3572591efe3c.png)

Navigation:
![pages_nav](https://cloud.githubusercontent.com/assets/493458/9402809/31bd2fd6-47e1-11e5-8966-740d6602061c.png)

Layouts:
![layouts](https://cloud.githubusercontent.com/assets/493458/9402813/3c75d91e-47e1-11e5-94c8-b13b59d128ed.png)

User Edit:
![user](https://cloud.githubusercontent.com/assets/493458/9402832/731df870-47e1-11e5-90db-d2f840917496.png)


It should go in public beta testing next week and it will be under wolfcms github account so anybody can download it, give it a spin and report issues/improvements etc. before it gets merged into master.

I must say that this was not just new theme, rather overall code cleanup with few new tweaks and intention to make it more easier for use for plugin devs.

**Comment by mtylerb** [comment]
I am looking forward to the beta, then. I will post screenshots of what we come up with.

**Comment by mtylerb** [comment]
Will this be posted as a specific branch?  Is there any way to get some sort of notification when this is up?

**Comment by project79** [comment]
Yes, it will be under branch:five before it goes into develop and fibally
master.

We will write a blog and forum post to let people know and test too.

**Comment by mtylerb** [comment]
Thanks Dejan.  Is there an ETA on updates being pushed into five?  I noticed it's still XTHML right now.

**Comment by project79** [comment]
Not really. Still have some cleaning to do.

It's under my account. You can check it out.

**Comment by mtylerb** [comment]
I'm assuming it's the 0.8.1 version.  Just hasn't been merged into 0.8.3.1?

**Comment by project79** [comment]
Yes. And it won't until I make a Pull against wolfcms directly. Hopefully I'll end this in the next few days (too much stuff on the day job, so little time for everything else)

**Comment by mvdkleijn** [comment]
@project79 Before I forget... make sure to cleanup the branch before you create the PR.

**Comment by project79** [comment]
Ah yes. The config file. Ok.

**Comment by mtylerb** [comment]
Any updates on this front?

**Comment by project79** [comment]
Yes. I restarted my work to finish this 2 days ago as I had urgent surgery and was not able to do any work for the last 2 months. I hope I will had time to release it in the upcoming days as there is just cleaning and few things to be done.

**Comment by mtylerb** [comment]
Is there anything I can do to help?  Seems the work gods have decided I shall be unemployed for the near future.  So...  I'm free.

**Comment by mvdkleijn** [comment]
@project79 - You want to comment on this one? :smile:

**Comment by mtylerb** [comment]
You're teasing me.

**Comment by project79** [comment]
Yup.
This is on hold for now.
