### ISSUE TITLE
Make entire buttons in admin's sidebar clickable

### ISSUE THREAD

**Issue by dedlfix** [wolfcms/wolfcms#483]
To have the entire button clickable (not just text and image) change and add these CSS properties:

wolf/admin/stylesheets/admin.css
line 341:
#sidebar p.button {
  padding: 0 0 0 20px;

line 360:
#sidebar p.button img {
  margin: -10px 10px 0 0;

line 370:
#sidebar p.button a {
  display: block;
  padding: 10px 20px 0 0;

**Comment by project79** [comment]
I'll close this in favor of 2.0
