### ISSUE TITLE
Empty spaces due to expanded_rows cookie

### ISSUE THREAD

**Issue by godDLL** [wolfcms/wolfcms#615]
If one was to open the Pages tab and then create a _child page_ to any page, _expand the parent_ to show the child and then _delete the child_ this last change (deletion) wouldn't be reflected in the `expanded_rows` cookie.

Which will mean that an empty space is inserted under the _parent page_ whenever you view the Pages tab. This is the `<ul class="sortable child">` element being inserted, even though that child doesn't exist anymore.

**Comment by project79** [comment]
Sorry, didn't see this before.
We are almost done with the new backend UI and will revise javascript afterwards.
Thanks for the tip
