### ISSUE TITLE
htaccess error Apache 2.4, Fedora 21, "Request exceeded the limit of 10 internal redirects"

### ISSUE THREAD

**Issue by macropin** [wolfcms/wolfcms#620]
It looks like newer versions of apache are fussy about missing / in mod_rewrite rules. 

The standard .htaccess generates the following error on Apache 2.4 / Fedora 21. 

    [Wed Apr 08 12:34:36.094619 2015] [core:error] [pid 1145] [client 127.0.0.1:35085] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://localhost/?articles/2015/04/08/my-first-article

The fix is to change the rewrite rule to include a forward slash:

    RewriteRule ^(.*)$ /index.php?WOLFPAGE=$1 [L,QSA]

**Comment by mvdkleijn** [comment]
cool, thanks for the info. i will add it later today

**Comment by mvdkleijn** [comment]
Fixed in `develop`
