### ISSUE TITLE
On the webpage there are html tags printed out in my menu

### ISSUE THREAD

**Issue by mattisebastian** [wolfcms/wolfcms#624]
When changing a menu like shown in the screenshot below:

![bearbeitung](https://cloud.githubusercontent.com/assets/2878488/7433335/83f69b24-f030-11e4-8b3b-b36f556af14c.png)

It is not possible to display a plain name on the website. Much rather some html tags are shown as well.
![fehler1](https://cloud.githubusercontent.com/assets/2878488/7433329/7aeb47b4-f030-11e4-93c8-56a0c0a3762c.png)

Technical stuff:

- Wolf CMS 0.7.5

At the moment I cannot give more information regarding the underlying software / databases. But if it is neccessary for you to reproduce the error I will find that out.
Feel free to inquire about more details regarding the issue.

Thank you.

**Comment by mvdkleijn** [comment]
looks like this could be a problem in the textile parser. have you tried to put spaces before and after the / signs?

the parser is probably getting confused.

besides that, you should probably upgrade to the latest version of wolf cms

**Comment by mattisebastian** [comment]
I fixed it by changing the order of the sections, seems very random. Thanks for pointing out the version problem. Unfortunately I don't have access to the server right now.

**Comment by dedlfix** [comment]
This is not an error of Wolf CMS nor Textile. This Tab should have no Filter set, because a self written snippet is used to parse this tab.
