### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by blr21560** [wolfcms/wolfcms#626]
Hi,
In the backend, the format of date (i.e. bottom of page) is bad in french.

**Comment by project79** [comment]
What you mean it's bad in french? Not European style date like dd/mm/yyyy or something else?

**Comment by blr21560** [comment]
img1 = in edit page the format page is yyyy-mm-dd
img2 = the text is in french it's good but the is in english (Sun, 5 Jul 2015 ).
In french it's Sam 5 Jul 2015

![img1](https://cloud.githubusercontent.com/assets/201661/8528337/ca529fda-2412-11e5-8e96-e0970c9b6525.png)
![img2](https://cloud.githubusercontent.com/assets/201661/8528344/d2f5a8ee-2412-11e5-81e1-76a855a561d7.png)

**Comment by mvdkleijn** [comment]
I understand what you mean. That date is generated by PHP. We'll take a look.
