### ISSUE TITLE
Open redirect vulnerability in wolf cms

### ISSUE THREAD

**Issue by AKA-Clay** [wolfcms/wolfcms#629]
An open redirect vulnerability in admin page 

And in login[redirect]=/wolf/admin/ input.
 if we change input to login[redirect]=http://Google.com 
After login will be redirected to Google .

Vulnerability is submitted on cxsecurity and packetstormsecurity after 1 day 

Tnx to wolf cms developer team

**Comment by mvdkleijn** [comment]
Fix released
