### ISSUE TITLE
Textile Filter causes deprecated warnings

### ISSUE THREAD

**Issue by mtylerb** [wolfcms/wolfcms#633]
PHP versions greater than 5.5 cause a Warning message that fills the error_log.  The deprecated function is the use of /e in the preg_replace on line 1553 of classTextile.php.

```PHP
// -------------------------------------------------------------
	function footnoteRef($text)
	{
		return preg_replace('/(?<=\S)\[([0-9]+)([\!]?)\](\s)?/Ue',
			'$this->footnoteID(\'\1\',\'\2\',\'\3\')', $text);
	}
```
I'm currently using the following as a replacement on my installation, but I'm not 100% on all the repercussions this change might have had, besides the error no longer being produced.

```PHP
// -------------------------------------------------------------
	function footnoteRef($text)
	{
		return preg_replace_callback('/(?<=\S)\[([0-9]+)([\!]?)\](\s)?/U',
			function($x) { return eFunction($x[1], $x[2], $x[3]); }, $text);
	}
```

**Comment by mvdkleijn** [comment]
The original parser is no longer maintained nor available I believe. We will probably need to replace it with https://github.com/textile/php-textile

**Comment by mtylerb** [comment]
Agreed, though for the meantime just a quick fix to remove the deprecated warnings would be nice.
