### ISSUE TITLE
The third-party plugin "form" suddenly stopped working.

### ISSUE THREAD

**Issue by bekkr** [wolfcms/wolfcms#635]
I've got two websites on two different web hostings. I use the user-contributed plugin "form" for my websites.  Suddenly for both sites I started to get a message: "An error has ocurred and the email has not been sent."

In the helper email.php I've changed the protocol to 'smtp' from 'mail, the form started to send again but with some issues. 

So I wonder what can cause that problem? Probably there was an update for PHP that is not capable with the latest version of helper email.php?

Thanks in advance.

**Comment by mvdkleijn** [comment]
It would help if you added what version of Wolf CMS, PHP and the plugin you're using. Also please indicate if anything was changed by you or the hosting company.

**Comment by bekkr** [comment]
It's WolfCMS 0.8.1 for one site  and Wolf CMS 0.8.3.1 for another. 
The plugin is the latest version of Form by Nic Wortel. https://www.wolfcms.org/repository/111

Nothing has been changed by me. I just noticed today that forms don't work anymore on both different hostings.

**Comment by bekkr** [comment]
On one of the hostings I could get an access to php.ini. 

With this settings below  configured in php.ini, I made the form to work again.

SMTP                                          
smtp_port                                    
sendmail_from                                 
username                                       
password                                      

Is there any way to configure the sendmail settings inside email.php? (for another hosting)

**Comment by mvdkleijn** [comment]
You can take a look at the public variables in https://github.com/wolfcms/wolfcms/blob/master/wolf/helpers/Email.php

You can set them either directlt or through passing an array of options to the initialize method.

Also see https://www.wolfcms.org/phpdoc/latest/Helpers/Email.html

**Comment by bekkr** [comment]
I've already seen those variables and I suppose there is not solution to setup "sendmail' protocol (only smtp), as I've already done in php.ini for another hosting.

**Comment by chellmann** [comment]
using the sendmail protocol you have to setup the sendmail agent at 
system level - on shared hosting likely impossible.

Try to use Mandrillapp.com as SMTP server, should work fine.

bekkr schrieb:

**Comment by project79** [comment]
This is Email helper fault and here is possible fix: https://github.com/wolfcms/wolfcms/issues/638

**Comment by mvdkleijn** [comment]
Closing this in favour of #638
