### ISSUE TITLE
eMail Helper Error on HTML mails

### ISSUE THREAD

**Issue by SamBrishes** [wolfcms/wolfcms#638]
Hello,

The eMail Helper does not work on HTML Mails. I always get the following error message (on PHP 5.6.11):

```
Warning: mail(): Multiple or malformed newlines found in additional_header in \php5.6.11\htdocs\wolf\wolf\helpers\Email.php on line 1022
```

I search for this problem and found a solution on [Stackoverflow](http://stackoverflow.com/a/30897935). The default HTML mail seems now to work after I commented out the line 780 (see below), but this is probably not the best solution for it. ^^

```php
	$hdr .= "Content-Type: multipart/alternative; boundary=\"" . $this->_alt_boundary . "\"" . $this->newline;
	$hdr .= $this->_getMimeMessage() . $this->newline;
	$hdr .= "--" . $this->_alt_boundary . $this->newline;

	$hdr .= "Content-Type: text/plain; charset=" . $this->charset . $this->newline;
	$hdr .= "Content-Transfer-Encoding: " . $this->_getEncoding() . $this->newline;
	//$hdr .= $this->_getAltMessage() . $this->newline . "--" . $this->_alt_boundary . $this->newline;

	$hdr .= "Content-Type: text/html; charset=" . $this->charset . $this->newline;
	$hdr .= "Content-Transfer-Encoding: quoted/printable";

	if ($this->_getProtocol() == 'mail') {
		$this->_header_str .= $hdr;
		$this->_finalbody = $this->_body . $this->newline . "--" . $this->_alt_boundary . "--";
		return;
	}

	$hdr .= $this->newline . $this->newline;
	$hdr .= $this->_body . $this->newline . $this->newline . "--" . $this->_alt_boundary . "--";

	$this->_finalbody = $hdr;
	return;
```

Sincerely,
Sam.

**Comment by project79** [comment]
Well, it seems I have the same problem: https://www.wolfcms.org/forum/topic4362new-posts.html
I will check if your fix works for me too, tomorrow.

**Comment by stevensmith007** [comment]
Same here. Tried this fix, still didn't work. Spent hours trying to find another fix, still didn't work. Ended up reverting to PHP 5.3 on the server instead of PHP 5.5

**Comment by mvdkleijn** [comment]
I'll take a look at this if someone can provide an actual test case... What are you doing and how. No descriptions, step by step instructions on repeating the issue including any code needed.

**Comment by stevensmith007** [comment]
Using at least PHP 5.5.29

    use_helper('Email');
    $emailTo = 'email@domain.com'

    $message = '<p>Hello<br/>This is an HTML <strong>email</strong> message</p>';
		
    $email = new Email();
    $email->from('from@domain.com', 'John Doe');
    $email->to('to@domain.com');
    $email->subject('A custom subject here');
    $email->message($message);
    $email->setMailtype('html'); //important, has to be HTML type to get the error

    if ($email->send()) {
	    echo 'all good';
    }
    else {
	    echo 'not good';
    }

Checking the error log, you should get something like 

> Warning: mail(): Multiple or malformed newlines found in additional_header in \php5.6.11\htdocs\wolf\wolf\helpers\Email.php on line 1022

**Comment by stevensmith007** [comment]
Using at least PHP 5.5.29 on a server.

    use_helper('Email');

    $message = '<p>Hello<br/>This is an HTML <strong>email</strong> message</p>';
		
    $email = new Email();
    $email->from('from@domain.com', 'John Doe');
    $email->to('to@domain.com');
    $email->subject('A custom subject here');
    $email->message($message);
    $email->setMailtype('html'); //important, has to be HTML type to get the error

    if ($email->send()) {
	    echo 'all good';
    }
    else {
	    echo 'not good';
    }

Checking the error log, you should get something like 

> Warning: mail(): Multiple or malformed newlines found in additional_header in \php5.6.11\htdocs\wolf\wolf\helpers\Email.php on line 1022

**Comment by project79** [comment]
Same here and exactly the same error.
I did some googling and it seems that escaping headers feature for mail() protocol has changed from PHP 5.4 and up, thus causing this error and not sending anything.
I'm using Form plugin made by Nic, but the result is same.

**Comment by mvdkleijn** [comment]
You mean the mail() function. We didn't catch it because we don't have any automated tests for the Email helper since it was an import from another project.

I'll have to switch my laptop from PHP 7 back to PHP 5.x to work in this but I think I have a fix. Messy weekend planning, but somewhere this weekend should be possible.

**Comment by mvdkleijn** [comment]
The mail function in PHP had a potential security issue which they fixed. The Email helper stuffs the multipart stuff in the header argument to the mail function, which worked before but is incorrect.

I'll have to recode it a little to move the multipart stuff to the body argument.
