### ISSUE TITLE
[Security] Salt does not reset on password change

### ISSUE THREAD

**Issue by felberj** [wolfcms/wolfcms#640]
Resetting the password does not reset the salt

affected lines:

[LoginController](https://github.com/wolfcms/wolfcms/blob/f363e541c5517cd4630190f6d1930c80b0ad008c/wolf/app/controllers/LoginController.php#L186)

[UserController](https://github.com/wolfcms/wolfcms/blob/3d8363ef632dbd5794aaca9e8fba416bcd04227e/wolf/app/controllers/UserController.php#L292)

**Comment by mvdkleijn** [comment]
Hmmm... good point. Resetting the salt would make sense.
