### ISSUE TITLE
Redirect loop on login page when using https

### ISSUE THREAD

**Issue by anton-tsyganenko** [wolfcms/wolfcms#644]
![2016-02-22-111019_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4764069/13212965/85e88dba-d956-11e5-93f3-d393636ee41e.png)
The cyan rectangle is my domain. Also see https://www.wolfcms.org/forum/topic4377.html.

**Comment by mvdkleijn** [comment]
I assume you verified that your https setup is working with plain html files....

Check if the public URL is https in config.php, that shouldn't matter but maybe we have a bug here.

I personally use https on several sites and it works fine, though I use it both in the front- and backends.

**Comment by anton-tsyganenko** [comment]
The public url starts with http://

**Comment by anton-tsyganenko** [comment]
changed URL_PUBLIC to https,  but it has no effect.

**Comment by anton-tsyganenko** [comment]
https works, but in some browsers I get an error that connection is untrusted. Probably it's because I used free startssl certificate.

**Comment by mvdkleijn** [comment]
Well, if you get an untrusted warning it's probably on a mobile browser... Not all certificates are good for all browsers. I suggest you drop startssl which offers partially broken certs for free and use https://letsencrypt.org instead. Their certificates work in all browsers as far as I know.

Just to be clear: are you still getting the redirects or just the certificate warning?

Please note that the use-https setting in Wolf simply forces you to https... you can turn it off and manually go to https://yoursite/admin and login. You might get a warning on submit of the form but if you get a redirect, its probably a redirect by the web server, not Wolf.

**Comment by anton-tsyganenko** [comment]
I'm still getting redirection error.

I get certificate warning in desktop firefox and tor browser. I'm not sure if I can use let's encrypt on my hosting, but I'll try, thanks.

If I turn USE_HTTPS off I get lots of warnings and scripts are being blocked, so it's almost impossible to use the backend.

**Comment by mvdkleijn** [comment]
Hmmm sounds like there might be an issue with the server setup. I haven't encountered the behavior you're describing apart from when I had an accidental redirect in my web server config. I don't suppose you can show me that?

As for the letsencrypt certificate, you can do validation in several ways... this means you could do validation manually and download the certificate to your laptop (for example) so you can upload it to your hosting provider.

**Comment by anton-tsyganenko** [comment]
You mean /etc/httpd/conf/httpd.conf? I have a read permission on it.

**Comment by anton-tsyganenko** [comment]
The certificate problems were caused by wrong installation of the certificate (I didn't install the CA certificate). But redirecting issue is still open.

**Comment by mvdkleijn** [comment]
Good to hear you got the certificate issue resolved.

Yeah I meant httpd.conf or the file with your virtual host config if you have that. That way I can possibly replay the issue. I'll setup a clean install anyway to try and replicate the problem.

**Comment by anton-tsyganenko** [comment]
This is httpd.conf: https://gist.github.com/anton-tsyganenko/19f1cef8ad53ff6465fb

but virtual host files are stored separately, and I don't have read access to them.

**Comment by anton-tsyganenko** [comment]
I set USE_HTTPS to false and forced https usage in web server settings, so now the problem looks to be solved for me, but I'm still interested to know the reason of such a strange behavior.

**Comment by mvdkleijn** [comment]
As near as I can tell, the most likely cause is something in your virtual host config. The use_https setting only forces http:// to https:// in the admin url.

Without access to the vhost config its going to be difficult to judge correctly. It almost sounds like https was being redirected to http, causing a loop. Maybe something inserted by the hoster?

Can I ask what hosting provider you're using?

**Comment by anton-tsyganenko** [comment]
I use profitserver.ru.

**Comment by mvdkleijn** [comment]
Closing this as everything points to a problem with the hosting provider's setup, which we cannot support.
