### ISSUE TITLE
Sketch out 2.0 architecture for team

### ISSUE THREAD

**Issue by mvdkleijn** [wolfcms/wolfcms#655]
DoD:
- Sketch exists
- Sketch communicated to team
- Techs & versions listed where possible
- Separate sketches for admin interface and actual site

**Comment by godDLL** [comment]
What is WolfCMS overall status, would you say? 
Seems somewhat stale.

**Comment by mvdkleijn** [comment]
I'm on a summer break dude. Wolf CMS 2 is totally different in base setup. It needs some time.
