### ISSUE TITLE
Switched to Fork CMS

### ISSUE THREAD

**Issue by jeroendesloovere** [wolfcms/wolfcms#656]
Hi,

I've used Wolf CMS in the past for a year or two, before I used Frog CMS for some years.
But then I switched to [Fork CMS](http://www.fork-cms), since I missed some things.

**Comment by mvdkleijn** [comment]
@jeroendesloovere I don't appreciate this "issue". Very bad form as far as I'm concerned.

Wolf CMS is most definitely being maintained.

**Comment by project79** [comment]
Besides the "inappropriate issue", that cms is not that good and there are far better apps out there so there is no need for such comments here. 
I wanted to write you a big reply but that would be just a waste of my time. Plus, your issue sounds more like Jehovah's witness folks knocking on my door...

**Comment by 0ae0** [comment]
Wow this is so enraging that I created an account just to say I'll never ever _EVER_ use Fork CMS. How dare you go on people's projects to advertise yours in such a shitty manner. That "everything is allowed as long as I can get people to visit my homepage" attitude is loathsome! 
I am still discovering WolfCMS but finally I find a CMS that lets me build my pages as I want and for which content is easy to produce! This is great, thank you.
