### ISSUE TITLE
Image Upload Error

### ISSUE THREAD

**Issue by CodeNinjaSensei** [wolfcms/wolfcms#658]
_Notice_ - Please send security issues to wolfcms (at) gmail (dot) com
### Expected behaviour

Upload File Completed
### Actual behaviour

Logged in as Admin and any other power user, used multiple browsers.  Receiving 
"File has not been uploaded!
### Steps to reproduce the problem

Logged in as multiple users, using MS Edge and Google Chrome. 
#### Additional information
- Wolf CMS version: 0.8.1
- DB type and version:
- HTTP server type and version:

**Comment by project79** [comment]
I just checked and file upload works fine.

How big is the file?
It is usually associated with PHP and how the upload_max_filesize is set there (in php.ini file). I had this problem long time ago.

By default the limit is 2MB and if your file is bigger it will automatically be rejected producing error.
