### ISSUE TITLE
Website inaccessible

### ISSUE THREAD

**Issue by dajare** [wolfcms/wolfcms#663]
At the moment, the Wolf website cannot be reached. If anyone needs some access to documentation, it can still be found at the [Read the Docs URL][r] = [http://wolf-cms.readthedocs.io/en/latest/][r].

Also, most (all?) of the site can be accessed [on the Wayback Machine][1]. And note, too, that the "docs" are Markdown files and [available on Github][2], see e.g. the [Functions listing][3].

Hopefully a more satisfactory solution will be found at some point!

\[**updated**\]

[r]: http://wolf-cms.readthedocs.io/en/latest/
[1]: https://web.archive.org/web/20170502055616/https://www.wolfcms.org/
[2]: https://github.com/wolfcms/docs.wolfcms.org
[3]: https://github.com/wolfcms/docs.wolfcms.org/blob/master/docs/development/functions.md

**Comment by negru** [comment]
Can I make a donation? I can help with SSL certificates or hosting
