### ISSUE TITLE
Is wolfcms dead?

### ISSUE THREAD

**Issue by dsazup** [wolfcms/wolfcms#672]
Judging by activity in this repo and website, looks like its dead. Do people still use it? I used it in the past on a few websites, and it's time for an update. I was thinking to just rebuild those sites in another cms, but don't really want to. I might just write an update for the cms and maintain a fork, if this repository is dead 🤔

**Comment by swloopit** [comment]
i use it! but at this moment I do not actively contribute to development.there are structural problems that require a lot of time to revise the code. :(

**Comment by svanlaere** [comment]
Its fair to consider Wolf abandoned, maintaining a fork seems reasonable.

**Comment by SamBrishes** [comment]
Hello,

that's really sad to hear, but understandable. I had really fun to play with the Wolf CMS, such fun, that I decided to create a small own fork of your system. I call it Fox CMS, and I try to "bring it to 2018" step-by-step (to provide a faster update cycle). The first alpha version isn't finished yet, but can already viewed [on my develop branch](https://github.com/SamBrishes/FoxCMS/tree/develop).

Thanks for the awsome work on the Wolf CMS!

Sincerely,
Sam.

**Comment by dan-ddb** [comment]
@mvdkleijn So is there any plan to elect someone to lead the Wolf CMS project now that you are leaving? I would be interested in having a discussion about this. We have many client sites running various types of Wolf CMS and would benefit from continuing to fix bugs and things.
