### ISSUE TITLE
404 redirection

### ISSUE THREAD

**Issue by elivestudio** [wolfcms/wolfcms#680]
*Notice* - Please send security issues to wolfcms (at) gmail (dot) com

### Actual behaviour

Hi, I install Wolf on local machine using Sqlite and it worked perfectly. However, I am trying to use this on my website but after customizing my layout every new page I add displays 404 page not found. How can I fix this

#### Additional information

- Wolf CMS version: 
- DB type and version: 
- HTTP server type and version:

**Comment by dajare** [comment]
More information needed. But presumably this is past stale by now, so closing.
