### ISSUE TITLE
wolfcms.org error :(

### ISSUE THREAD

**Issue by negru** [wolfcms/wolfcms#681]
DB Connection failed: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by peminator** [comment]
yeah, hope u not lettin in down? also function reference page is very missed :(

**Comment by kimperator** [comment]
Hello, you can get the reference page as backup on archive.org http://web.archive.org/web/20180831172705/http://wolfcms.org/wiki/

**Comment by dajare** [comment]
You can also use the ReadTheDocs documentation (it is full and current) at the "generic" URL:

https://wolf-cms.readthedocs.io/

That's the best place to consult them, actually.
