### ISSUE TITLE
http://www.wolfcms.org/ site will not load

### ISSUE THREAD

**Issue by SRD75** [wolfcms/wolfcms#684]
*Notice* - Please send security issues to wolfcms (at) gmail (dot) com

### Expected behaviour

I expected the site http://www.wolfcms.org/ to load okay.

### Actual behaviour

I see an error "This site can’t be reached. www.wolfcms.org took too long to respond."

### Steps to reproduce the problem

Try and load http://www.wolfcms.org/ in the browser.

**Comment by dajare** [comment]
Duplicate of  #663
