### ISSUE TITLE
Our WolfCMS login won't work after migrating to HTTPS

### ISSUE THREAD

**Issue by SRD75** [wolfcms/wolfcms#685]
*Notice* - Please send security issues to wolfcms (at) gmail (dot) com

### Expected behaviour

I should be able to login @ https://www.example.com/admin/login

### Actual behaviour

After entering username and password and clicking Login, the page refreshes and nothing else happens.

### Steps to reproduce the problem

Clear your cookies for the domain. Switch from HTTP to HTTPS in the database. Try to login, and it may fail.

#### Additional information

- Wolf CMS version: unknown, can't login to check
- DB type and version: MySQL 10.1.44-MariaDB
- HTTP server type and version: Linux / LiteSpeed Server

**Comment by dajare** [comment]
This strikes me as odd ... I've got a number of sites running Wolf with HTTPS and there's never been a problem of this kind. I'm just on vanilla Apache, though - could LiteSpeed have anything to do with it?
